title: "Andrea R. Molino, ScM, PhDc"
description: Andrea Molino's personal website

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: andrea-molino-epi
    email: amolino29@gmail.com
    linkedin: andrea-molino-epi

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
